[general]
figure_size = [89, 89]
fontsizes = [0, 5, 5]
capsize=5
face_color='#785ef0'
sessions = [1, 2, 3, 4, 5, 6, 7, 8]

[[panels]]
labels = ['', 'Session', 'Correlation']

[[panels]]
labels = ['', 'Session', 'Jaccard similarity']

[[panels]]
fontsizes = [0, 5, 5, 5]
marker_color=['#648fff', '#fe6100']
labels = ['', 'Session', 'Normalised size', 'Model', 'Empirical']

[[panels]]
marker_color=['#dc267f', '#785ef0']
labels = ['', 'Model', 'Empirical']