[general]
figure_size = [89, 89]
fontsizes = [0, 5, 5, 5]
colormap="coolwarm"

[[panels]]
labels = ['','Contrast heterogeneity', 'Grid coarseness',
          '']
ticks = [[0.01, 0.25, 0.5, 0.75, 1.0], [1.0, 1.1, 1.2, 1.3, 1.4, 1.5]]
bounds = [0.5, 1.0]

[[panels]]
labels = ['','Contrast heterogeneity', 'Grid coarseness',
          'Accuracy']
ticks = [[0.01, 0.25, 0.5, 0.75, 1.0], [1.0, 1.1, 1.2, 1.3, 1.4, 1.5]]
bounds = [0.5, 1.0]

[[panels]]
labels = ['','Coupling decay factor', 'Maximum coupling strength',
          'Jaccard similarity']
ticks = [[0.0, 0.15, 0.3 , 0.45, 0.6], [0.0, 15.0, 30.0, 45.0, 60.0]]
bounds = [0.0, 1.0]

[[panels]]
labels = ['','Contrast heterogeneity', 'Grid coarseness',
          'Synchronization']
ticks = [[0.01, 0.25, 0.5, 0.75, 1.0], [1.0, 1.1, 1.2, 1.3, 1.4, 1.5]]
bounds = [0.0, 1.0]