# Condition numbers matching the actual experiment
mean_contrast = 0.5
num_subjects = 8
num_training_sessions = 8
num_blocks = 30
num_conditions = 25
num_contrast_heterogeneity = 5
num_grid_coarseness = 5
min_contrast_heterogeneity = 0.01
max_contrast_heterogeneity = 1
min_grid_coarseness = 1
max_grid_coarseness = 1.5
