# Increased condition numbers for extended simulations
mean_contrast = 0.5
num_training_sessions = 8
num_blocks = 10 # 30
num_conditions = 100  # 900
num_contrast_heterogeneity = 10 # 30
num_grid_coarseness = 10 # 30
min_contrast_heterogeneity = 0.01
max_contrast_heterogeneity = 1
min_grid_coarseness = 1
max_grid_coarseness = 1.5